name = "owned-greeter-ignusmart"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]

[setting.salt]
defaultValue = "owned-greeter-ignusmart"

[contract.Greeter]
artifact = "Greeter"
salt = "<%= settings.salt %>"
